version: "3"
services:
  webapp:
    build: .
    image: app:v1
    ports:
      - "80:8080"
    volumes:
      - "/root/.m2:/root/.m2"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: qpalwosk10
      MYSQL_DATABASE: demo
    ports:
      - "3333:3306"
    volumes:
      - $PWD/db:/var/lib/mysql
